---
title: "Accounting for R2 performance"
author: "Sean Trott and Pam Rivière"
date: "August 15, 2025"
output:
  html_document:
    keep_md: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 300, fig.format = "png")
```


```{r include=FALSE}
library(tidyverse)
library(lme4)
library(viridis)
library(ggridges)
library(broom)
library(ggcorrplot)
library(lmerTest)

all_colors <- viridis::viridis(10, option = "magma")
my_colors <- all_colors[c(1, 4, 7, 9)]  # Selecting specific colors from the palette
```

# Load data

## Disambiguation performance 

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/multilingual_disambiguation/src")
directory_path <- "../data/processed/distances/"
csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_distances <- bind_rows(csv_list) %>%
  mutate(
    model_name = sub(".*/", "", mpath)
  ) %>%
  mutate(language = str_to_title(language))


df_original_models_r2 = df_distances %>%
  group_by(model_name, multilingual, language, n_params, Layer) %>%
  summarise(r = cor(Distance, mean_relatedness)) %>%
  mutate(r2 = r ** 2) %>%
  group_by(model_name, n_params, multilingual, language) %>%
  summarise(max_r2 = max(r2))  %>%
  mutate(log_params = log10(n_params))


nrow(df_original_models_r2)

df_best_layers = df_distances %>%
  group_by(model_name, multilingual, language, n_params, Layer) %>%
  summarise(r = cor(Distance, mean_relatedness)) %>%
  mutate(r2 = r ** 2) %>%
  group_by(model_name, n_params, multilingual, language) %>%
  slice_max(r2, n = 1) %>%  # Get the layer with max r2
  ungroup() %>%
  select(model_name, language, Layer, max_r2 = r2)  # Keep the best layer number


df_original_models_r2 %>%
  group_by(language, multilingual) %>%
  summarise(mean_r2 = mean(max_r2))


### layerwise_r2
df_layerwise_r2 = df_distances %>%
  group_by(model_name, multilingual, language, n_params, Layer) %>%
  summarise(r = cor(Distance, mean_relatedness)) %>%
  mutate(r2 = r ** 2) %>%
  select(model_name, multilingual, language, n_params, Layer, r2)

```

## Attention capacity

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/multilingual_disambiguation/src")
directory_path <- "../data/processed/attentions/"
csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_all_models <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 1,
         Head = Head + 1) %>%
  mutate(
    model_name = sub(".*/", "", mpath)
  ) %>%
  mutate(language = str_to_title(language))

table(df_all_models$mpath)
table(df_all_models$language)
table(df_all_models$multilingual)
table(df_all_models$model_name)



## Processing
df_all_models = df_all_models %>%
  mutate(disambiguating_prev_diff = Attention - prev_token_attention,
         disambiguating_next_diff = Attention - next_token_attention)


df_attn_by_head = df_all_models %>%
  group_by(model_name, language, multilingual, Layer, Head, n_params) %>%
  summarise(mean_attention = mean(Attention),
            mean_prev_attention = mean(prev_token_attention),
            mean_next_attention = mean(next_token_attention),
            mean_diff_prev = mean(disambiguating_prev_diff),
            mean_diff_next = mean(disambiguating_next_diff)) %>%
  group_by(model_name, language, n_params) %>%
  mutate(z_attention = scale(mean_attention),
         z_prev_attention = scale(mean_prev_attention),
         z_next_attention = scale(mean_next_attention),
         z_diff_prev = scale(mean_diff_prev),
         z_diff_next = scale(mean_diff_next))



df_capacity = df_attn_by_head %>%
  group_by(model_name, n_params, language, multilingual) %>%
  summarise(
    max_attn = max(mean_attention)
  )

nrow(df_capacity)


df_attn_best_layer = df_attn_by_head %>%
  # inner_join(df_best_layers, by = c("model_name", "language", "Layer")) %>%
  group_by(model_name, language, multilingual, n_params) %>%
  summarise(max_attn = max(mean_attention))
nrow(df_attn_best_layer)

df_attn_all_layers = df_attn_by_head %>%
  group_by(model_name, language, multilingual, n_params, Layer) %>%
  summarise(max_attn = max(mean_attention))
nrow(df_attn_all_layers)

df_attn_all_layers = df_attn_by_head %>%
  group_by(model_name, language, multilingual, n_params, Layer) %>%
  summarise(max_attn = max(mean_attention),
            mean_attn = mean(mean_attention)) %>%
  group_by(model_name, language) %>%
  arrange(Layer) %>%
  mutate(max_attn_cumulative = cummax(max_attn),
         mean_attn_cumulative = cummean(mean_attn)) 

```

## Isotropy

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/multilingual_disambiguation/src")
directory_path <- "../data/processed/isotropy/"
csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_original_models <- bind_rows(csv_list) %>%
  filter(Layer > 0) %>%
  mutate(
    model_name = sub(".*/", "", mpath)
  ) %>%
  mutate(language = str_to_title(language))

table(df_original_models$language)
table(df_original_models$multilingual)
table(df_original_models$model_name)


df_best_layers = df_distances %>%
  group_by(model_name, multilingual, language, n_params, Layer) %>%
  summarise(r = cor(Distance, mean_relatedness)) %>%
  mutate(r2 = r ** 2) %>%
  group_by(model_name, n_params, multilingual, language) %>%
  slice_max(r2, n = 1) %>%  # Get the layer with max r2
  ungroup() %>%
  select(model_name, language, Layer, max_r2 = r2)  # Keep the best layer number

# Now get CI from those specific layers
df_isotropy = df_original_models %>%
  group_by(model_name, n_params, Layer, language, multilingual) %>%
  summarise(mean_dist = mean(mean_dist),
            mean_centered_isotropy = mean(centered_isotropy),
            mean_intra_sentence_similarity = mean(intra_sentence_similarity))

df_isotropy_best_layer = df_isotropy %>%
  inner_join(df_best_layers, by = c("model_name", "language", "Layer")) %>%
  ungroup() %>%
  select(model_name, language, multilingual, mean_ci = mean_centered_isotropy) 


```


## Tokenization

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/multilingual_disambiguation/src")
directory_path <- "../data/processed/tokens/"
csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_original_models <- bind_rows(csv_list) %>%
  mutate(
    model_name = sub(".*/", "", mpath)
  ) %>%
  mutate(language = str_to_title(language))

table(df_original_models$language)
table(df_original_models$multilingual)
table(df_original_models$model_name)

df_models_tokens = df_original_models %>%
  group_by(model_name, multilingual, language, n_params) %>%
  summarise(mean_tokens_target = mean(num_tokens_target),
            mean_tokens_dw = mean(num_tokens_disambiguating),
            mean_tokens_total = mean(num_tokens_total)) %>%
  mutate(log_params = log10(n_params)) %>%
  select(-n_params, -log_params) 
nrow(df_models_tokens) 
  

```

## Merge data

Layerwise data.

**TODO**: Figure out what's getting dropped.

```{r}
df_isotropy_subset = df_isotropy %>%
  ungroup() %>%
  select(model_name, Layer, mean_centered_isotropy, language,
         mean_intra_sentence_similarity, mean_dist)

df_all_layers = df_layerwise_r2 %>%
  inner_join(df_models_tokens) %>%
  inner_join(df_attn_all_layers) %>%
  inner_join(df_isotropy_subset)

nrow(df_all_layers)

```



## Merge data (2)

Just best R2.

```{r}


df_all_data = df_original_models_r2 %>%
  inner_join(df_models_tokens) %>%
  inner_join(df_attn_best_layer) %>%
  inner_join(df_isotropy_best_layer)
nrow(df_all_data)


```



# Analysis 

```{r}

### Direct model comparison
df_all_layers = df_all_layers %>%
  group_by(model_name) %>%
  mutate(max_layer = max(Layer)) %>%
  mutate(layer_depth = Layer / max_layer)

# Now compare R^2 for different linear models
df_all_layers$log_params = log10(df_all_layers$n_params)
models <- list(
  "Baseline" = "r2 ~ layer_depth + log_params + (1|model_name)",
  "Mean CI" = "r2 ~ mean_centered_isotropy + layer_depth + log_params + (1|model_name)",
  "Mean Tokens (Target)" = "r2 ~ mean_attn_cumulative + layer_depth + log_params + (1|model_name)",
  "Max. Attn." = "r2 ~ mean_attn_cumulative + layer_depth + log_params +(1|model_name)",
  "Multilingual" = "r2 ~ multilingual + layer_depth + log_params + (1|model_name)",
  "Multilingual + Predictors" = "r2 ~ multilingual + mean_centered_isotropy + mean_tokens_target + mean_attn_cumulative + layer_depth + log_params + (1|model_name)",
  "Predictors" = "r2 ~ mean_centered_isotropy + mean_tokens_target + mean_attn_cumulative + layer_depth + log_params + (1|model_name)"
)

r2_comparisons <- map_dfr(names(models), function(name) {
  fit_model <- lmer(as.formula(models[[name]]), data = df_all_layers)
  tibble(
    model = name,
    r_squared = summary(fit_model)$r.squared,
    aic = AIC(fit_model)
  )
})

print(r2_comparisons)

r2_comparisons = r2_comparisons %>%
  mutate(aic_rescaled = aic - max(aic))
r2_comparisons


r2_comparisons %>%
  ggplot(aes(x = reorder(model, aic_rescaled),
             y = aic_rescaled)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_minimal() +
  labs(x = "Predictor", y = "AIC (Rescaled)") +
  theme(text = element_text(size = 15),
        legend.title = element_blank()) 

r2_comparisons %>%
  arrange(aic_rescaled)


model_full = lmer(data = df_all_layers,
                r2 ~ multilingual + 
                  mean_centered_isotropy + mean_tokens_target + max_attn + 
                  layer_depth + log10(n_params) +
                  (1 + layer_depth |model_name))
model_no_ml = lmer(data = df_all_layers,
                r2 ~ mean_centered_isotropy + mean_tokens_target + max_attn + 
                  layer_depth + log10(n_params) +
                  (1|model_name))

anova(model_full, model_no_ml)
summary(model_full)





model_ml_effect = lmer(data = df_all_layers,
                r2 ~ multilingual +
                  layer_depth + log10(n_params) +
                  (1 + layer_depth |model_name))
summary(model_ml_effect)


df_all_layers %>%
  ggplot(aes(x = max_attn,
             y = r2,
             color = multilingual)) +
  geom_point(alpha = .6) +
  geom_smooth(method = "lm") +
  theme_minimal()


df_all_layers %>%
  group_by(multilingual) %>%
  summarise(mean_r2 = mean(r2),
            se_r2 = sd(r2)/sqrt(n())) %>%
  ggplot(aes(x = multilingual,
             y = mean_r2)) +
  geom_bar(stat = "identity") +  # Add stat = "identity" to use the actual values
  geom_errorbar(aes(ymax = mean_r2 + se_r2,  # Remove redundant x and y in aes
                    ymin = mean_r2 - se_r2),
                width = 0.2) +  # Optional: add width for cleaner error bars
  theme_minimal()

df_all_layers$resid = residuals(model_no_ml)

df_all_layers %>%
  group_by(multilingual) %>%
  summarise(mean_r2 = mean(resid),
            se_r2 = sd(resid)/sqrt(n())) %>%
  ggplot(aes(x = multilingual,
             y = mean_r2)) +
  geom_bar(stat = "identity") +  # Add stat = "identity" to use the actual values
  geom_errorbar(aes(ymax = mean_r2 + se_r2,  # Remove redundant x and y in aes
                    ymin = mean_r2 - se_r2),
                width = 0.2) +  # Optional: add width for cleaner error bars
  labs(x = "Multilingual",
       y = "Residuals (Predictors)") +
  theme_minimal()


model_full = lmer(data = df_all_layers,
                r2 ~ multilingual + mean_centered_isotropy + # mean_tokens_target + max_attn + 
                  # layer_depth + log10(n_params) +
                  (1 + layer_depth |model_name))


```


